### ISSUE TITLE
Error while managing widget with live preview

### ISSUE THREAD

**Issue by sanzeeb3** [themegrill/social-icons#20]
### EXPLANATION OF THE ISSUE

I got this call to undefined function `get_socicon()` while trying to manage widget with live preview.

### STEPS TO REPRODUCE THE ISSUE

1. Go to appearance->widgets
2. Click on manage with live preview
3. It shows a fatal error call to undefined function.

**Comment by shivapoudel** [comment]
It was due to some reason the `social-icons/includes/libraries/` directory was missing during svn upload or plugin release. Its resolved in SI 1.7.0.
